### ISSUE TITLE
Configure the default LIMIT

### ISSUE THREAD

**Issue by GromNaN** [stanlemon/rest-bundle#39]
The default number of items per page is currently hardcoded in the [DefaultCriteria](https://github.com/stanlemon/rest-bundle/blob/master/Object/Criteria/DefaultCriteria.php#L9).
It would be nice if this could be in the bundle configuration.

Example: 

``` yaml
lemon_rest:
    defaults:
        limit: 500
```
